#!/usr/bin/env bash
#  configure web-02 to be identical to web-01
# shellcheck disable=SC2154
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
HOST_NAME=$(hostname)
HEADER="http {\\n\\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$HEADER/" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default
sudo service nginx start
