#!/usr/bin/env bash
# A script that configures a new Ubuntu machine to respect requirements.
apt-get update
apt-get install software-properties-common -y
apt-get update
apt-get install haproxy=2.0.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server web1 54.157.173.233:80 check
        server web2 100.26.222.187:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
