#!/usr/bin/env bash
# A script that configures a new Ubuntu machine to respect requirements.
apt-get update
apt-get install software-properties-common -y
apt-get update
apt-get install haproxy=2.0.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server web1 54.157.173.233:80 check
        server web2 100.25.28.162:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
