#!/usr/bin/env bash
# A script that configures a server to the requirements
mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default 
service nginx stop
pkill nginx
service nginx start
