#!/usr/bin/env bash
# Script for shorter version of previous task via daemon manager
mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
pkill nginx
