#!/usr/bin/env bash
# Infinite loop Bash Script that creates and deletes a script

echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/myscript.pid; exit" SIGQUIT

i=2
while ((i < 10));
do
	echo To infinity and beyond
	sleep 2
done
