#!/usr/bin/env bash
# FizzBuzz using while loop
i=1
while  ((i<=100));
do
	if ((i%3 == 0 && i%15 != 0)); then
		echo Fizz
	elif ((i%5 == 0 && i%15 != 0)); then
		echo Buzz
	elif ((i%15 == 0)); then
                echo FizzBuzz
	else
		echo $i
        fi
        ((i++))
done
