#!/usr/bin/env bash
# iterating 5-4_bad_luck_8_is_your_chance using while loop
i=0
while  ((i<=9));
do
	if ((i==3)); then
		echo bad luck
	elif ((i==7)); then
                echo good luck        
	else	
		echo Best School
	fi
        ((i++))
done
