#!/usr/bin/env bash
# iterating 6-superstitious_numbers using while loop
i=1
while  ((i<= 20));
do
        echo $i
	case $i in
		4)
			echo bad luck from China
			;;
		9)
			echo bad luck from Japan
			;;
		17)
			echo bad luck from Italy
			;;
	esac
        ((i++))
done
